# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNzsZpjVR9vSzIUGulcjt4dFnd3ycM8E
"""

nia = int(input())
ayay= list(map(int, input().split()))
sary = int(input())
ansie = []
for i in range(nia):
    for j in range(i + 1, nia):
        if ayay[i] + ayay[j] == s:
            ansie.append(i)
            ansie.append(j)
if len(ansie) == 0:
    print("Not Found!")
else:
    ansie.sort()
    for i in ansie:
        print(i, end=" ")