# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eCzL5_gN63hprYq_LbPI4NT-1v2vH5g0
"""

import numpy as np


n, m = map(int, input().split())
matrices = [np.array([list(map(float, input().split())) for _ in range(m)]) for _ in range(n)]


max_det, selected_pair = float('-inf'), None

for i in range(n):
    for j in range(i + 1, n):
        det_ij = np.linalg.det(matrices[i] @ matrices[j])
        if det_ij > max_det:
            max_det, selected_pair = det_ij, (i, j)


result_matrix = matrices[selected_pair[1]] @ matrices[selected_pair[0]]

result_matrix_inv = np.linalg.inv(result_matrix)


for row in result_matrix_inv:
    print(" ".join(f"{x:.3f}" for x in row))