# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RuOD56SjxlmeITjEItNhYvf5QXlBYM4W
"""

class Player:
    def __init__(seelf, name, health):
        seelf.name = name
        seelf.health = health
        seelf.score = 0

class Card:
    def __init__(seelf, name, damage):
        seelf.name = name
        seelf.damage = damage

def play_game(player1, player2, cards):
    for card1 in cards:
        for card2 in cards:
            try:
                damage1 = card1.damage
                damage2 = card2.damage

                if damage1 > damage2:
                    player1.score += 1
                elif damage1 < damage2:
                    player2.score += 1

                player1.health -= damage2
                player2.health -= damage1

            except AttributeError:
                print("Invalid Command.")

    print(f"{player1.name} -> Score: {player1.score}, Health: {player1.health}")
    print(f"{player2.name} -> Score: {player2.score}, Health: {player2.health}")

if __name__ == "__main__":
    names = input().split()
    healths = list(map(int, input().split()))
    damages = list(map(int, input().split()))


    player1 = Player(names[0], healths[0])
    player2 = Player(names[1], healths[1])

    cards = [Card("A", damages[0]), Card("B", damages[1]), Card("C", damages[2])]


    play_game(player1, player2, cards)