# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tgu8mmS73YexqnR-BQRWpQtc1h4k5Zo1
"""

def decrypt_string(cipher_text: str) -> str:
    positions, encrypted_chars = cipher_text.split(" ")
    positions = list(map(int, positions.split()))
    decrypted_chars = [""] * len(positions)
    for i, char in enumerate(encrypted_chars):
        decrypted_chars[positions[i]] = char
    return "".join(decrypted_chars)

